local opt = vim.opt

opt.number = true
opt.swapfile = false
opt.cmdheight = 0
opt.backup = false
opt.writebackup = false
opt.updatetime = 300
opt.timeout = true
opt.timeoutlen = 300
opt.undofile = true
opt.undodir = vim.fn.stdpath("data") .. "/undo"
opt.splitright = true
opt.splitbelow = true
opt.showmode = false
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.cursorline = true
opt.signcolumn = "yes"
opt.colorcolumn = "80"
opt.relativenumber = true
opt.smartindent = true
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.softtabstop = 2
opt.clipboard = "unnamedplus"
opt.iskeyword:append("-")
opt.mouse = "a"
opt.termguicolors = true
opt.hidden = true
opt.autoread = true
opt.showmatch = true
opt.ignorecase = true
opt.smartcase = true
opt.incsearch = true
opt.hlsearch = true
opt.inccommand = "nosplit"
opt.wrap = false
